### ISSUE TITLE
The relay add-on menu incorrectly displayed when user is signed out

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay-add-on#165]
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit

**Browsers tested on:**
Firefox

**Preconditions:**
The relay add-on is installed.

**Steps to reproduce:**

1. Navigate to Stage server and log in with an existing account.
2. Observe the relay add-on menu.
3. Sign out.
4. Observe the relay add-on menu.

**Actual result:**
The relay add-on menu is incorrectly displayed.

**Expected result:**
The relay add-on menu is correctly displayed showing a sign in option.

![relay add-on menu issue when signed out](https://user-images.githubusercontent.com/79697848/137473875-947c1d4b-def1-450e-a2ac-a11ff6789fa6.gif)

**Comment by groovecoder** [comment]
This is a known issue, also filed here: https://github.com/mozilla/fx-private-relay-add-on/issues/28

It needs some Product & UX input to decide if/how we want to handle add-on sign-outs. Recommendation:

When the user signs out of the website, we should detect this with the add-on, and sign them out of the add-on too.
