### ISSUE TITLE
Domain-based aliases are not shown in the new Add-on context submenus

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay-add-on#231]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a Subdomain (domain) name set;
- Have at least one Domain-based alias created
- Have the latest add-on version for Stage installed;

#### Steps to reproduce:
1. Go to any site that displays a fill-able email field;
2. Right click on the field;
3. Open the “Firefox Relay” submenu;
4. Open the “Use Existing Alias from this site…” submenu and observe it;
5. Open the “Recent Aliases” submenu and observe it;

#### Expected result:
- The submenus should offer for use the Domain-based aliases somewhere;

#### Actual result:
- The submenus do not offer the Domain-based alias anywher ;

#### Notes:
- It was not mentioned anywhere if the Domain-based aliases should or should not be offered somewhere in the submenus;
- See attached media:
![domal1](https://user-images.githubusercontent.com/85748693/145382784-7242ad54-f405-48df-90fa-8d923985ab71.png)
![domal2](https://user-images.githubusercontent.com/85748693/145382788-2fc1c865-009e-457b-9e7b-4378f49d002b.png)
![domal3](https://user-images.githubusercontent.com/85748693/145382793-217ffdb2-afea-4f50-b780-6f0f2a3f604a.png)

**Comment by Vinnl** [comment]
I think this is intentional? Since the custom subdomain aliases are primarily intended for coming up with an email alias offline, whereas random aliases are recommended because they can't be linked together - see also e.g. "Generate New Alias" always generating random aliases.
