### ISSUE TITLE
The “Firefox Relay” submenu from the context menu closes by itself when the user hovers over it after the first time they open the context menu

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay-add-on#263]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with or without an active subscription;
- Have the latest version of the Stage Firefox Relay extension installed;

#### Steps to reproduce:
1. Go to any page that has a fill-able email field;
2. Right click on the field, opening the context menu;
3. Hover over the “Firefox Relay” option;
4. Hover over a different option;
5. Hover again over the “Firefox Relay” option;
6. Observe the behavior;

#### Expected result:
- There are no visible problems in the interactions;

#### Actual result:
- When the user opens the context menu for the first time and hovers over the “Firefox Relay” option, the submenu closes by itself;

#### Notes:
- Hovering again on the option opens it without issues;
- This always happens the first time a user opens the submenu; 
- There do not seem to be different behaviors depending on the number or type of generated aliases; 
- See attached media:
![contextmenu2](https://user-images.githubusercontent.com/85748693/150964129-38194995-3742-4c05-94c2-fafd54df4712.gif)

**Comment by lloan** [comment]
This is fixed by #369 

@maxxcrawford should we mark this one complete/done?

**Comment by maxxcrawford** [comment]
@lloan Good call! 

Closed by #369
