### ISSUE TITLE
Latest update causes some webpage text to become huge

### ISSUE THREAD

**Issue by salmonbishop** [mozilla/fx-private-relay-add-on#275]
Since the last update, certain portions of website text have become much larger than they are normally displayed.

With Relay disabled:
![redditnormal](https://user-images.githubusercontent.com/98851219/152054048-1b68a9cf-5f10-4d5f-8ec8-9defbddf62d7.png)

With Relay enabled:
![redditrelay](https://user-images.githubusercontent.com/98851219/152054096-0bcd2f78-1054-4c2c-9f5a-86f8c548756f.png)

Firefox 97.0 beta channel
Windows 11

**Comment by maxxcrawford** [comment]
@salmonbishop Hey there! This has been resolved. Please make sure you're [updated to the latest version](https://support.mozilla.org/en-US/kb/how-update-add-ons) of the release: `2.2.2`
