### ISSUE TITLE
[Button] Private relay button makes the email form look broken at joann.com 

### ISSUE THREAD

**Issue by dholbert** [mozilla/fx-private-relay-add-on#29]
STR:
 1. Install the private relay addon.
 2. Visit https://www.joann.com/ and scroll down to the bottom of the page, to see the "Sign up for email & save" enter-your-email box

ACTUAL RESULTS:
- "Sign up for email & save" text is covered up
- right border on the widget is clipped/covered

EXPECTED RESULTS:
- Text & widget-border should still be visible.

**Comment by codemist** [comment]
When rechecking the site, the button now appears to work.
