### ISSUE TITLE
No mention of "Premium" in the logo name for premium users

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay-add-on#322]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
The Relay extension is installed in the browser. (the version we got from Maxx: https://github.com/mozilla/fx-private-relay-add-on/actions/runs/2266514754)
The user has an active subscription.

**Steps to reproduce:**

1. Navigate to Relay page and log in.
2. Go to a different website that has an email field and click the Relay icon in the email field.
3. Observe the logo and the name.

**Actual result:**
No mention of premium in the logo name. "Firefox Relay" is displayed instead of "Firefox Relay Premium". See [Figma ](https://www.figma.com/file/iz6X5c6IwuU6ii9128YFmP/Premium-Relay-Add-On?node-id=0%3A1) for reference. 
Same for add-on menu.

**Expected result:**
"Firefox Relay Premium" name is displayed for premium users in both field icon menu and add-on menu.

**Notes:**
N/A

![No premium mentioned in logo name](https://user-images.githubusercontent.com/79697848/166662307-be3c11b4-9954-4b94-a975-db1fbcf342ce.png)

![no premium add-on menu](https://user-images.githubusercontent.com/79697848/166662684-8c6d8f4b-b66f-4d40-8f6c-935abdf28348.png)

**Comment by maxxcrawford** [comment]
Leaving this as a WONTFIX for right now, after talking to UX!
