### ISSUE TITLE
Relay logos are different

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay-add-on#323]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
The Relay extension is installed in the browser. (the version we got from Maxx: https://github.com/mozilla/fx-private-relay-add-on/actions/runs/2266514754)

**Steps to reproduce:**

1. Navigate to Relay page and log in.
2. Go to a different website that has an email field and click the Relay icon in the email field.
3. Compare the icon in the field with the logo in the menu.

**Actual result:**
The logos are different. The colors for logo are inverted.

**Expected result:**
The logos are similar.

**Notes:**
Same issue occurs for toolbar icon and add-on menu.
Please check the email footer logo too.

![diff logo field icon menu](https://user-images.githubusercontent.com/79697848/166664829-60b1f859-56b2-45a7-8e35-dd7ed9bc19a5.png)

![different logo add-on menu](https://user-images.githubusercontent.com/79697848/166664838-89a19dd8-170b-47e5-b989-6bad8cdb7927.png)

![email logo](https://user-images.githubusercontent.com/79697848/166667632-32bd8990-9c82-41ca-aae9-f6e134696d29.png)

**Comment by maxxcrawford** [comment]
@Bianca-O I pushed up a fix for this, but this did not adjust the email logo. That is a seperate issue that needs to be filed in the [other repo.](https://github.com/mozilla/fx-private-relay)
