### ISSUE TITLE
Cannot use local label storage with custom masks

### ISSUE THREAD

**Issue by Vinnl** [mozilla/fx-private-relay-add-on#341]
Basically, the issue is that [we're attaching labels to the locally-cached `relayAddresses` object](https://github.com/mozilla/fx-private-relay-add-on/blob/a00a5160f0a2e49b663024db2811283d129d9a6d/src/js/relay.firefox.com/get_profile_data.js#L275-L287), which doesn't include custom masks (`domainAddresses`). I think this is [how we always did it](https://github.com/mozilla/fx-private-relay-add-on/blob/d655efc63be03dd615dc328be74d8a278223bfb0/src/js/relay.firefox.com/get_profile_data.js#L374), so I expect that this never worked?

> Spot-check fails:
> 
> 1. run locally on 127.0... (i.e. `python manage.py runserver` & `npm run watch`)
> 2. run the extension locally (`npm run web-ext-run`).
> 3. On an account with server-side label storage enabled, you should be able to see a non-empty PATCH request being sent to the API containing your label. ✅ 
> 4. Go to http://127.0.0.1:8000/accounts/profile/
> 5. Add a label to a domain address
> 6. Go to http://127.0.0.1:8000/accounts/settings/
> 7. Disable server-side storage
> 8. Go back to http://127.0.0.1:8000/accounts/profile/
>    * [ ] Label is still there (from add-on storage) on the domain address
> 9. Change the label value
> 10. Refresh the page
>    * 💔 The label value is gone

_Originally posted by @groovecoder in https://github.com/mozilla/fx-private-relay/pull/1969#pullrequestreview-980345179_

**Comment by maxxcrawford** [comment]
It worked previously because we scrapped data from this site. 

FWIW: The `relayAddresses` object contains all masks used on the dashboard.

**Comment by maxxcrawford** [comment]
Resolved!
