### ISSUE TITLE
Filling Relay email doesn't un-disable Sign in button

### ISSUE THREAD

**Issue by martin-kokos** [mozilla/fx-private-relay-add-on#368]
On website: https://www.sony.co.uk/mysony/login
Pick relay email. Sign in button is still disabled.
Add a letter to the email and the Sign in button activates.

It appears as if some javascript on the website doesn't notice there has been something typed into the email input field.

**Comment by codemist** [comment]
Great news! This issue is resolved in our next release. Thank you for sharing the concern.
