### ISSUE TITLE
[l10n]: request to add 'pt-PT' locale to the repo

### ISSUE THREAD

**Issue by peiying2** [mozilla/fx-private-relay-add-on#421]
Per community request, please add locale `pt-PT` to the repo. I have added the locale in Pontoon so the community can start localization

**Comment by Vinnl** [comment]
@peiying2 I think there's nothing we need to do here, assuming Pontoon automatically creates the `pt-PT` folder. The extension automatically picks them up, and we also don't have a TOML file that lists a predefined list of locales we support.

**Comment by peiying2** [comment]
OK, let me close the issue.
