### ISSUE TITLE
enhancement: mobile addon support missing

### ISSUE THREAD

**Issue by jrconlin** [mozilla/fx-private-relay-add-on#430]
Many customers only have a mobile device, or use a mobile device preferably to a desktop or larger format device. It would be useful to have similar features available on Fenix, (ability to quickly generate a masked email, or insert the mask phone number on forms.)

**Comment by cadeyrn** [comment]
Duplicate of #391.

**Comment by Vinnl** [comment]
Thanks for triaging, I'll close this to keep discussion contained to that issue.
