### ISSUE TITLE
New "!" does not dismissa after clicking popup. 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay-add-on#501]

**Comment by D4n2021** [comment]
Thanks for reporting, I have this issue since several weeks now. What is the "!" supposed to indicate anyways?

**Comment by D4n2021** [comment]
![image](https://user-images.githubusercontent.com/20766261/233792002-01739151-0151-414d-8272-cb41520e6556.png)

**Comment by maxxcrawford** [comment]
@D4n2021 It should only show up when we push a new features or news announcement (and then should disappear whenever you open the panel one time)

**Comment by D4n2021** [comment]
Ok! Does your commit from 3 days ago mean that with the next merge this issue will be fixed?

**Comment by D4n2021** [comment]
@maxxcrawford
https://github.com/mozilla/fx-private-relay-add-on/pull/500
awesome!! Thanks so much! 😀👌 🥳

**Comment by D4n2021** [comment]
@maxxcrawford Do you know an approximate ETA for the merge to release into the addon (and conclusively become visible on this page https://addons.mozilla.org/en-US/firefox/addon/private-relay/versions/ ) ?
I'm assuming several people have access to the addon's account, right? (https://addons.mozilla.org/en-US/firefox/user/4757633/)

**Comment by Vinnl** [comment]
Hi @D4n2021, releasing is a manual process that happens some time after merging, after our testers have approved the new version, so unfortunately it won't be available right away. We'll try to get it out as soon as possible, sorry for the inconvenience.

**Comment by D4n2021** [comment]
@Vinnl Ok. Is there a place somewhere to follow the testing-progress, on https://treeherder.mozilla.org/ or so for example?

**Comment by Vinnl** [comment]
@D4n2021 Sorry, I was on holiday. Unfortunately, there is not, however, this fix should have been included in [version 2.7.1](https://github.com/mozilla/fx-private-relay-add-on/releases/tag/2.7.1), which [is now available](https://addons.mozilla.org/en-GB/firefox/addon/private-relay/).
