### ISSUE TITLE
allow selecting previously created aliases on popup

### ISSUE THREAD

**Issue by zanona** [mozilla/fx-private-relay-add-on#58]
Instead of giving the user only the option to generate a new alias or manage current ones on a separate page, it would be great to have a list of already created aliases, so we can click on those in order to fill the input underneath.

![image](https://user-images.githubusercontent.com/32017/90006054-7b4cec80-dc98-11ea-9181-9c9aed673c2a.png)

**Comment by maxxcrawford** [comment]
Hey there! I wanted to let anyone watching this issue that we've made some progress on this front. Our next release contains a feature where if you right click on a field, you can reuse a previous alias. We'll continue to work on this feature as well. 🙌 

https://github.com/mozilla/fx-private-relay-add-on/releases/tag/2.1.1
