### ISSUE TITLE
Website broken with relay icon enabled (DOM error)

### ISSUE THREAD

**Issue by SosthenG** [mozilla/fx-private-relay-add-on#90]
I noticed a website completly broken when the option "Show Relay icon inemail fields on websites" is enabled.
Website: https://dl2.dyinglightgame.com/fr/

Looks like the entire DOM is removed after scrolling a little bit, with the following error in the console:
`DOMException: Node.removeChild: The node to be removed is not a child of this node`

Disabling the option "Show Relay icon" in the extension settings removes the issue.

**Comment by maxxcrawford** [comment]
Our refactored in-page icon-injection should address this issue. Please re-open is still present. Thanks!
