### ISSUE TITLE
"If a site doesn't work, let us know"

### ISSUE THREAD

**Issue by ph818** [mozilla/fx-private-relay-add-on#91]
This link on the faq page (https://relay.firefox.com/faq) took me to the extension feedback page. I'm not sure if you want people to leave reviews of the extension with X website didn't work or not, or to click through to github and leave an issue here.

The website that (understandably) did not accept relay was https://cloud.ibm.com/registration

**Comment by pendantry** [comment]
I'm in the same situation. Got a problem with Firefox Relay, followed that link inviting me to 'let you know' there's a problem, and... can't.
